package edu.fdu.se.bean;

public class AndroidTag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_tag.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_tag.tag_name_full
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String tagNameFull;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_tag.tag_name_short
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String tagNameShort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_tag.tag_sha_id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String tagShaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_tag.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String projectName;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_tag
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public AndroidTag(Integer id, String tagNameFull, String tagNameShort, String tagShaId, String projectName) {
		this.id = id;
		this.tagNameFull = tagNameFull;
		this.tagNameShort = tagNameShort;
		this.tagShaId = tagShaId;
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_tag
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public AndroidTag() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_tag.id
	 * @return  the value of android_tag.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_tag.id
	 * @param id  the value for android_tag.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_tag.tag_name_full
	 * @return  the value of android_tag.tag_name_full
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getTagNameFull() {
		return tagNameFull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_tag.tag_name_full
	 * @param tagNameFull  the value for android_tag.tag_name_full
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setTagNameFull(String tagNameFull) {
		this.tagNameFull = tagNameFull == null ? null : tagNameFull.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_tag.tag_name_short
	 * @return  the value of android_tag.tag_name_short
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getTagNameShort() {
		return tagNameShort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_tag.tag_name_short
	 * @param tagNameShort  the value for android_tag.tag_name_short
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setTagNameShort(String tagNameShort) {
		this.tagNameShort = tagNameShort == null ? null : tagNameShort.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_tag.tag_sha_id
	 * @return  the value of android_tag.tag_sha_id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getTagShaId() {
		return tagShaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_tag.tag_sha_id
	 * @param tagShaId  the value for android_tag.tag_sha_id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setTagShaId(String tagShaId) {
		this.tagShaId = tagShaId == null ? null : tagShaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_tag.project_name
	 * @return  the value of android_tag.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_tag.project_name
	 * @param projectName  the value for android_tag.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName == null ? null : projectName.trim();
	}
}