package edu.fdu.se.bean;

import java.util.Date;

public class AndroidRepoCommitWithBLOBs extends AndroidRepoCommit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_repo_commit.commit_log
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	private String commitLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_repo_commit.commit_log_full
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	private String commitLogFull;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_repo_commit
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public AndroidRepoCommitWithBLOBs(Integer id, String commitId, Integer branchId, String branchName, String tagName,
			Date commitDatetime, Date commitTimestamp, Integer issdkfile, String commitLog, String commitLogFull) {
		super(id, commitId, branchId, branchName, tagName, commitDatetime, commitTimestamp, issdkfile);
		this.commitLog = commitLog;
		this.commitLogFull = commitLogFull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_repo_commit
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public AndroidRepoCommitWithBLOBs() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_repo_commit.commit_log
	 * @return  the value of android_repo_commit.commit_log
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public String getCommitLog() {
		return commitLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_repo_commit.commit_log
	 * @param commitLog  the value for android_repo_commit.commit_log
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public void setCommitLog(String commitLog) {
		this.commitLog = commitLog == null ? null : commitLog.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_repo_commit.commit_log_full
	 * @return  the value of android_repo_commit.commit_log_full
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public String getCommitLogFull() {
		return commitLogFull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_repo_commit.commit_log_full
	 * @param commitLogFull  the value for android_repo_commit.commit_log_full
	 * @mbg.generated  Fri Dec 29 15:30:05 CST 2017
	 */
	public void setCommitLogFull(String commitLogFull) {
		this.commitLogFull = commitLogFull == null ? null : commitLogFull.trim();
	}
}