package edu.fdu.se.bean;

public class AndroidSDKJavaFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.id
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.file_name
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.file_full_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private String fileFullPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.sdk_version
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private Integer sdkVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private String subCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.sub_sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private String subSubCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column android_sdk_java_file.sub_sub_category_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    private String subSubCategoryPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_sdk_java_file
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public AndroidSDKJavaFile(Integer id, String fileName, String fileFullPath, Integer sdkVersion, String subCategory, String subSubCategory, String subSubCategoryPath) {
        this.id = id;
        this.fileName = fileName;
        this.fileFullPath = fileFullPath;
        this.sdkVersion = sdkVersion;
        this.subCategory = subCategory;
        this.subSubCategory = subSubCategory;
        this.subSubCategoryPath = subSubCategoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_sdk_java_file
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public AndroidSDKJavaFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.id
     *
     * @return the value of android_sdk_java_file.id
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.id
     *
     * @param id the value for android_sdk_java_file.id
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.file_name
     *
     * @return the value of android_sdk_java_file.file_name
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.file_name
     *
     * @param fileName the value for android_sdk_java_file.file_name
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.file_full_path
     *
     * @return the value of android_sdk_java_file.file_full_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public String getFileFullPath() {
        return fileFullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.file_full_path
     *
     * @param fileFullPath the value for android_sdk_java_file.file_full_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setFileFullPath(String fileFullPath) {
        this.fileFullPath = fileFullPath == null ? null : fileFullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.sdk_version
     *
     * @return the value of android_sdk_java_file.sdk_version
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public Integer getSdkVersion() {
        return sdkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.sdk_version
     *
     * @param sdkVersion the value for android_sdk_java_file.sdk_version
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setSdkVersion(Integer sdkVersion) {
        this.sdkVersion = sdkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.sub_category
     *
     * @return the value of android_sdk_java_file.sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.sub_category
     *
     * @param subCategory the value for android_sdk_java_file.sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory == null ? null : subCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.sub_sub_category
     *
     * @return the value of android_sdk_java_file.sub_sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public String getSubSubCategory() {
        return subSubCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.sub_sub_category
     *
     * @param subSubCategory the value for android_sdk_java_file.sub_sub_category
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setSubSubCategory(String subSubCategory) {
        this.subSubCategory = subSubCategory == null ? null : subSubCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column android_sdk_java_file.sub_sub_category_path
     *
     * @return the value of android_sdk_java_file.sub_sub_category_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public String getSubSubCategoryPath() {
        return subSubCategoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column android_sdk_java_file.sub_sub_category_path
     *
     * @param subSubCategoryPath the value for android_sdk_java_file.sub_sub_category_path
     *
     * @mbg.generated Tue Oct 31 09:29:10 CST 2017
     */
    public void setSubSubCategoryPath(String subSubCategoryPath) {
        this.subSubCategoryPath = subSubCategoryPath == null ? null : subSubCategoryPath.trim();
    }
}