package edu.fdu.se.bean;

public class AndroidPlatformFrameworkProject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_platform_framework_project.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_platform_framework_project.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_platform_framework_project.project_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String projectSubPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column android_platform_framework_project.project_sub_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	private String projectSubSubPath;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_platform_framework_project
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public AndroidPlatformFrameworkProject(Integer id, String projectName, String projectSubPath,
			String projectSubSubPath) {
		this.id = id;
		this.projectName = projectName;
		this.projectSubPath = projectSubPath;
		this.projectSubSubPath = projectSubSubPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table android_platform_framework_project
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public AndroidPlatformFrameworkProject() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_platform_framework_project.id
	 * @return  the value of android_platform_framework_project.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_platform_framework_project.id
	 * @param id  the value for android_platform_framework_project.id
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_platform_framework_project.project_name
	 * @return  the value of android_platform_framework_project.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_platform_framework_project.project_name
	 * @param projectName  the value for android_platform_framework_project.project_name
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName == null ? null : projectName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_platform_framework_project.project_sub_path
	 * @return  the value of android_platform_framework_project.project_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getProjectSubPath() {
		return projectSubPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_platform_framework_project.project_sub_path
	 * @param projectSubPath  the value for android_platform_framework_project.project_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setProjectSubPath(String projectSubPath) {
		this.projectSubPath = projectSubPath == null ? null : projectSubPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column android_platform_framework_project.project_sub_sub_path
	 * @return  the value of android_platform_framework_project.project_sub_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public String getProjectSubSubPath() {
		return projectSubSubPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column android_platform_framework_project.project_sub_sub_path
	 * @param projectSubSubPath  the value for android_platform_framework_project.project_sub_sub_path
	 * @mbg.generated  Sat Dec 30 14:47:32 CST 2017
	 */
	public void setProjectSubSubPath(String projectSubSubPath) {
		this.projectSubSubPath = projectSubSubPath == null ? null : projectSubSubPath.trim();
	}
}