package edu.fdu.se.gitrepo;

public class RepoConstants {
	public static String platform_frameworks_av_ = "/platform/frameworks/av/";
	public static String platform_frameworks_base_ = "/platform/frameworks/base/";
	public static String platform_frameworks_compile_libbcc_ = "/platform/frameworks/compile/libbcc/";
	public static String platform_frameworks_compile_linkloader_ = "/platform/frameworks/compile/linkloader/";
	public static String platform_frameworks_compile_llvm_ndk_cc_ = "/platform/frameworks/compile/llvm-ndk-cc/";
	public static String platform_frameworks_compile_mclinker_ = "/platform/frameworks/compile/mclinker/";
	public static String platform_frameworks_compile_slang_ = "/platform/frameworks/compile/slang/";
	public static String platform_frameworks_data_ = "/platform/frameworks/data/";
	public static String platform_frameworks_data_binding_ = "/platform/frameworks/data-binding/";
	public static String platform_frameworks_ex_ = "/platform/frameworks/ex/";
	public static String platform_frameworks_hardware_interfaces_ = "/platform/frameworks/hardware/interfaces/";
	public static String platform_frameworks_janktesthelper_ = "/platform/frameworks/janktesthelper/";
	public static String platform_frameworks_layoutlib_ = "/platform/frameworks/layoutlib/";
	public static String platform_frameworks_media_libvideoeditor_ = "/platform/frameworks/media/libvideoeditor/";
	public static String platform_frameworks_mff_ = "/platform/frameworks/mff/";
	public static String platform_frameworks_minikin_ = "/platform/frameworks/minikin/";
	public static String platform_frameworks_ml_ = "/platform/frameworks/ml/";
	public static String platform_frameworks_multidex_ = "/platform/frameworks/multidex/";
	public static String platform_frameworks_native_ = "/platform/frameworks/native/";
	public static String platform_frameworks_opt_bitmap_ = "/platform/frameworks/opt/bitmap/";
	public static String platform_frameworks_opt_bluetooth_ = "/platform/frameworks/opt/bluetooth/";
	public static String platform_frameworks_opt_calendar_ = "/platform/frameworks/opt/calendar/";
	public static String platform_frameworks_opt_carddav_ = "/platform/frameworks/opt/carddav/";
	public static String platform_frameworks_opt_chips_ = "/platform/frameworks/opt/chips/";
	public static String platform_frameworks_opt_colorpicker_ = "/platform/frameworks/opt/colorpicker/";
	public static String platform_frameworks_opt_com_google_android_ = "/platform/frameworks/opt/com.google.android/";
	public static String platform_frameworks_opt_com_google_android_googlelogin_ = "/platform/frameworks/opt/com.google.android.googlelogin/";
	public static String platform_frameworks_opt_datetimepicker_ = "/platform/frameworks/opt/datetimepicker/";
	public static String platform_frameworks_opt_emoji_ = "/platform/frameworks/opt/emoji/";
	public static String platform_frameworks_opt_inputconnectioncommon_ = "/platform/frameworks/opt/inputconnectioncommon/";
	public static String platform_frameworks_opt_inputmethodcommon_ = "/platform/frameworks/opt/inputmethodcommon/";
	public static String platform_frameworks_opt_mailcommon_ = "/platform/frameworks/opt/mailcommon/";
	public static String platform_frameworks_opt_mms_ = "/platform/frameworks/opt/mms/";
	public static String platform_frameworks_opt_net_ethernet_ = "/platform/frameworks/opt/net/ethernet/";
	public static String platform_frameworks_opt_net_ims_ = "/platform/frameworks/opt/net/ims/";
	public static String platform_frameworks_opt_net_lowpan_ = "/platform/frameworks/opt/net/lowpan/";
	public static String platform_frameworks_opt_net_voip_ = "/platform/frameworks/opt/net/voip/";
	public static String platform_frameworks_opt_net_wifi_ = "/platform/frameworks/opt/net/wifi/";
	public static String platform_frameworks_opt_photoviewer_ = "/platform/frameworks/opt/photoviewer/";
	public static String platform_frameworks_opt_setupwizard_ = "/platform/frameworks/opt/setupwizard/";
	public static String platform_frameworks_opt_sherpa_ = "/platform/frameworks/opt/sherpa/";
	public static String platform_frameworks_opt_telephony_ = "/platform/frameworks/opt/telephony/";
	public static String platform_frameworks_opt_timezonepicker_ = "/platform/frameworks/opt/timezonepicker/";
	public static String platform_frameworks_opt_vcard_ = "/platform/frameworks/opt/vcard/";
	public static String platform_frameworks_opt_widget_ = "/platform/frameworks/opt/widget/";
	public static String platform_frameworks_policies_base_ = "/platform/frameworks/policies/base/";
	public static String platform_frameworks_rs_ = "/platform/frameworks/rs/";
	public static String platform_frameworks_support_ = "/platform/frameworks/support/";
	public static String platform_frameworks_testing_ = "/platform/frameworks/testing/";
	public static String platform_frameworks_uiautomator_ = "/platform/frameworks/uiautomator/";
	public static String platform_frameworks_volley_ = "/platform/frameworks/volley/";
	public static String platform_frameworks_webview_ = "/platform/frameworks/webview/";
	public static String platform_frameworks_wilhelm_ = "/platform/frameworks/wilhelm/";

}
