package edu.fdu.se.mapper;

import edu.fdu.se.bean.AndroidBranch;
import edu.fdu.se.bean.AndroidBranchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AndroidBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    long countByExample(AndroidBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    int deleteByExample(AndroidBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    int insert(AndroidBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    int insertSelective(AndroidBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    List<AndroidBranch> selectByExample(AndroidBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") AndroidBranch record, @Param("example") AndroidBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_branch
     *
     * @mbg.generated Fri Dec 29 15:30:06 CST 2017
     */
    int updateByExample(@Param("record") AndroidBranch record, @Param("example") AndroidBranchExample example);
    
    
    
	List<AndroidBranch> selectAll();
	List<AndroidBranch> selectBranchByShortName(@Param("branchShortName")String branchShortName);
	List<AndroidBranch> selectBranchByShortNameAndProjName(@Param("branchShortName")String branchShortName,@Param("projName")String projectName);
	List<AndroidBranch> selectBranchAll(@Param("projName")String projName);
} 