package edu.fdu.se.mapper;

import edu.fdu.se.bean.AndroidRepoCommit;
import edu.fdu.se.bean.AndroidRepoCommitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AndroidRepoCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    long countByExample(AndroidRepoCommitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    int deleteByExample(AndroidRepoCommitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    int insert(AndroidRepoCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    int insertSelective(AndroidRepoCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    List<AndroidRepoCommit> selectByExample(AndroidRepoCommitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") AndroidRepoCommit record, @Param("example") AndroidRepoCommitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table android_repo_commit
     *
     * @mbg.generated Fri Nov 24 14:31:43 CST 2017
     */
    int updateByExample(@Param("record") AndroidRepoCommit record, @Param("example") AndroidRepoCommitExample example);
}